name: dropdown_search
description: Simple and robust Searchable Dropdown with item search feature, making it possible to use an offline item list or filtering URL for easy customization.
version: 5.0.3
homepage: https://github.com/salim-lachdhaf
git: https://github.com/salim-lachdhaf/searchable_dropdown
repository: https://github.com/salim-lachdhaf/searchable_dropdown

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: 0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:




  # example:
  fonts:
    - family: SongTi
      fonts:
        - asset: assets/fonts/feihuasong.ttf